### ISSUE TITLE
This app does not seem to pull the status of communication in ERPNext

### ISSUE THREAD

**Issue by adityaduggal** [semilimes/sendgrid_integration#1]
Hi,

I have followed the following steps:
1. Install the app in my production server
2. Install the app in my individual account
3. Create sendgrid account in erpnext
4. Created a sub-user in sendgrid for this account
5. Use sub-user name and password in the erpnext email account page
6. Created a API key and copy and pasted the same in the erpnext email account page with field API Key.

I am able to send emails using the sendgrid account but there is no update of the status whether the email is BOUNCED, OPEN or CLICKED.

**Comment by alex-melkoff** [comment]
Hi, @adityaduggal. After you hit "Save" button, API request will be sent with settings for webhook. If everything is fine, then you should be able to see a message on the top of Email Account settings page. If there was an error, then dialog with information about error should popup. So which of those two things happened?

**Comment by alex-melkoff** [comment]
@adityaduggal, please also note that communication status will be synced to the field "delivery_status", in doctype "Communication". According to field's description provided by developers:

> Integrations can use this field to set email delivery status

That's why this field was used to store status of sent messages, not field "status". Field "delivery_status" is hidden by default, so probably you will have to make it visible by customizing "Communication" from doctype customization settings.

**Comment by sagar-bhogayata** [comment]
I have the same issue I can send Email but didn't get status
(I Check delivery_status in Communication DocType but it's not Updating)
